// El guion es una historia automática y cinematográfica: cada paso recibe
// una fracción proporcional de la canción y no requiere ninguna acción manual.
const L=(who,text)=>({kind:'say',who,text});
const W=x=>({kind:'walk',to:x});
const P=hold=>({kind:'hold',hold});

export const LIGHTS=[
  {name:'Amabilidad',color:'#62df7d'},
  {name:'Justicia',color:'#ffd84a'},
  {name:'Valentía',color:'#ff9a45'},
  {name:'Perseverancia',color:'#b187ff'},
  {name:'Integridad',color:'#5f7dff'},
  {name:'Paciencia',color:'#79e4ee'},
  {name:'Determinación',color:'#ff5c70'},
];

export const ACTS=[
  {
    id:'room',kind:'room',name:'La habitación de las promesas',act:'I · La espera',
    width:720,spawn:118,guide:false,
    script:[
      P(1.2),
      L('Narración','Habías soñado esta noche con ilusión. Todo estaba listo.'),
      W(250),
      L('Narración','Horneaste el bizcocho con amor. Seis sillas esperando.'),
      W(382),
      L('Génesis','Lo preparé todo para nosotros…'),
      L('Narración','Pero pasaron las horas y nadie tocó a tu puerta.'),
      L('Narración','En la pantalla parecían juntos. En la mesa, estabas sola.'),
      W(510),
      L('Narración','A veces se confunde mirar historias con estar de verdad.'),
      L('Narración','Pide tu deseo, Génesis. Tu noche aún no termina.'),
      P(1.2),
      L('Narración','Soplaste la vela. La llama no murió: salió a buscarte.'),
      P(1.4),
    ],
  },
  {
    id:'alley',kind:'alley',name:'El callejón de las ventanas',act:'II · La chispa',
    width:980,spawn:72,guide:true,
    script:[
      L('Narración','La pequeña luz bajó las escaleras y te invitó a salir.'),
      W(260),
      L('Génesis','¿Hacia dónde me llevas con tanta prisa?'),
      L('Luz','Hacia la parte de ti que nunca pierde la esperanza.'),
      W(590),
      L('Narración','Una ventana se iluminó a lo lejos. La noche despertaba.'),
      W(900),
      L('Narración','Alguien abría paso entre las sombras, cuidando tu camino.'),
    ],
  },
  {
    id:'street',kind:'street',name:'El barrio que seguía despierto',act:'III · La señal',
    width:1420,spawn:75,guide:true,
    script:[
      L('Narración','Avanzaste por calles donde la ciudad dormía despierta.'),
      W(350),
      L('Narración','Cada farola se encendía justo al sentir tus pasos.'),
      W(720),
      L('Génesis','Siento que alguien camina adelante… protegiéndome.'),
      L('Luz','No quiere adelantarse, solo asegurarse de que no temas.'),
      L('Narración','Viste pantallas encendidas: la soledad de estar conectados.'),
      W(1060),
      L('Narración','En un charco, el cielo brillaba guardado para ti.'),
      W(1340),
    ],
  },
  {
    id:'garden',kind:'garden',name:'El jardín de las luces perdidas',act:'IV · La travesía',
    width:1660,spawn:70,guide:true,lights:[210,410,610,810,1010,1210,1410],
    script:[
      L('Narración','El asfalto dio paso a la brisa suave y al susurro de hojas.'),
      L('Narración','Siete almas resplandecían en el camino: tus virtudes.'),
      W(210),
      L('Luz','Amabilidad: tu don de cuidar a otros con infinita dulzura.'),
      W(410),
      L('Luz','Justicia: la nobleza de dar valor y respetarte a ti misma.'),
      W(610),
      L('Luz','Valentía: respirar profundo y caminar aun con miedo.'),
      W(810),
      L('Luz','Perseverancia: la fuerza de levantarte con una sonrisa.'),
      W(1010),
      L('Luz','Integridad: ser transparente y fiel a ti siempre.'),
      W(1210),
      L('Luz','Paciencia: la sabiduría serena de esperar lo que vale.'),
      W(1410),
      L('Luz','Determinación: el fuego en tu pecho que nunca se rinde.'),
      L('Génesis','¿Estas almas… de verdad estaban todas en mí?'),
      L('Luz','Siempre han sido tuyas. Esta noche saliste a verlas.'),
      W(1580),
    ],
  },
  {
    id:'bridge',kind:'bridge',name:'El puente sobre la ciudad',act:'V · El puente',
    width:1240,spawn:74,guide:true,
    script:[
      L('Narración','El sendero se elevó sobre el puente que abraza la ciudad.'),
      W(330),
      L('Génesis','Desde aquí el mundo parece tan calmo. Incluso lo que dolió.'),
      W(650),
      L('Luz','El dolor no borra tu valor. Enseña cuánto puedes brillar.'),
      W(960),
      L('Narración','Una sombra cálida dejó una flor en la baranda.'),
      W(1160),
    ],
  },
  {
    id:'plaza',kind:'plaza',name:'La plaza de los otros',act:'VI · Los otros',
    width:1900,spawn:72,guide:true,people:[280,540,800,1060,1320,1580],
    script:[
      L('Narración','En la plaza estaban las seis miradas de las sillas vacías.'),
      W(280),
      L('Simón','Vi tu mensaje… creí que felicitarte por foto bastaría.'),
      W(540),
      L('Nora','Me distraje buscando figurar donde no hacía falta.'),
      W(800),
      L('Lía','Me refugié en mi pantalla y olvidé llegar a tu mesa.'),
      W(1060),
      L('Mateo','Conté reacciones vacías y descuidé a quien me esperaba.'),
      W(1320),
      L('Abril','Me importó más publicar que compartir la noche contigo.'),
      W(1580),
      L('Joel','No hay excusa: fallé al momento en que debía estar.'),
      L('Génesis','No doy mis dones por rencor: los comparto de corazón.'),
      L('Narración','Compartió seis almas de luz. Pero guardó la más brillante.'),
      W(1820),
    ],
  },
  {
    id:'dawn',kind:'dawn',name:'Un amanecer para Génesis',act:'VII · El amanecer',
    width:1040,spawn:74,guide:false,
    script:[
      L('Narración','La cuesta final ascendía hacia los primeros rayos del alba.'),
      W(330),
      L('Narración','Al llegar a la cima, quien te guiaba se detuvo y se giró.'),
      W(570),
      L('Enmanuel','Siempre estuve aquí, cuidando tu camino.'),
      L('Enmanuel','Traigo la prueba de toda la luz que llevas en tu interior.'),
      L('Génesis','Regalé seis almas… creí que al final me quedaría vacía.'),
      L('Determinación','Dar amor no te vacía. Soy tu Determinación y soy eterna.'),
      W(690),
      L('Narración','El alma roja de la Determinación selló la carta.'),
      L('Enmanuel','Esta carta es para ti, Génesis. Léela con el corazón.'),
      P(1.8),
    ],
  },
];

const SOUL_WORDS=[
  'Cuidas con una dulzura pura y desinteresada. Tu bondad se nota en los detalles que nadie pide pero que alegran el alma, como preparar un bizcocho con amor para ver sonreír a otros.',
  'Tienes un corazón recto y sincero que busca siempre lo justo. Sabes dar valor y dignidad a los demás, y hoy aprendes también a honrar tu propio espacio y tus sentimientos.',
  'Tu valor no consiste en no tener miedo, sino en respirar hondo y seguir adelante. Enfrentas los días difíciles con la frente en alto y una nobleza admirable.',
  'No importa cuántas veces la vida se ponga cuesta arriba; siempre te levantas, te sacudes la tristeza y sigues construyendo tus sueños con la misma ternura.',
  'Eres transparente, genuina y leal a lo que sientes. En un mundo lleno de filtros y apariencias, tu autenticidad es un refugio de paz que no necesita fingir nada.',
  'Posees la madurez hermosa de saber escuchar, comprender y respetar los tiempos. Sabes que lo que realmente vale la pena en el corazón se teje despacio y con fe.',
  'Es la chispa sagrada que habita en tu pecho. Esa voluntad invencible que te sostiene de pie, que te recuerda quién eres y que te guía a través de cualquier noche hacia tu propio amanecer.',
];

export const LETTER=[
  {text:'Querida Génesis: esta historia y esta carta no nacen para darte nada que no sea ya tuyo. Las siete almas que cruzaron la noche representan las virtudes que iluminan todo lo que eres:'},
  ...LIGHTS.map((light,index)=>({...light,text:SOUL_WORDS[index]})),
  {text:'En la plaza decidiste compartir tus dones con quienes no llegaron a la cita, porque tu corazón es tan noble que no sabe responder con rencor. Pero tus dones no menguaron: lo hermoso que das al mundo permanece vivo en ti.'},
  {text:'Hoy en día es fácil perderse en pantallas donde todos parecen estar juntos mientras en silencio falta presencia real. Estar de verdad, mirarse a los ojos y cuidar a quien amamos vale infinitamente más que cualquier número o mensaje tardío.'},
  {text:'Esta carta es cariño y admiración sincera por la persona que eres. No necesitas demostrarle nada a nadie para merecer ser querida, escuchada y abrazada con devoción.'},
  {text:'Que nunca olvides la inmensa luz que llevas por dentro. Feliz cumpleaños, Génesis. Que la Determinación guíe siempre tus pasos, y recuerda que aquí siempre habrá un lugar seguro donde eres valorada exactamente por ser tú.'},
];
